### PR TITLE
TMC2130 DIAG tweaks v2

### PR DESCRIPTION
**Pull request by wavexx**
### Description

So it turned out my previous fix was enough to get a bit further, but still wasn't accurate enough.

As usual, the real behavior was a bit more subtle: DIAG is not cleared when writing to GCONF itself, but when the load itself disappears by either stopping or disabling motors (which _usually_ happened as a result of tmc2130 reconfiguration).

This PR reverts my old change. DIAG is not guaranteed to update immediately on the real TMC2130 when GCONF is update, however the current simulated behavior is more than adequate. We instead introduce proper DIAG reset, along with extra tests to check for this behavior.

### Behaviour/ Breaking changes

MK404 is now good enough to test the PowerPanic feature in the Prusa FW :)

### Have you tested the changes?

Works on my computer™

### CODE REVIEW

**Comment by wavexx** [comment]
cppcheck looks broken here.

**Comment by vintagepc** [comment]
Looks like clang-tidy may have been updated and is griping about new issues. I'll look into it :+1:

**Comment by wavexx** [comment]
I have a couple of warnings in w25x20cl and GLPrint from either cppcheck 2.3 or 2.4. Looking at the detailed output, this is coming mostly from clang-tidy. At least here with clang 11, tidy is so ultra verbose I just disabled it..

**Comment by vintagepc** [comment]
Yeah, some of the complains are excessive but it looks like there might be a few things that'd be good to clean up. I'll merge this and make a separate task for that.

**Pull request merged**
