### PR TITLE
Fix clang compile errors

### PR DESCRIPTION
**Pull request by GilesBathgate**
### Description

Hi, I like this project. I found a few compile issues, probably because my default compiler is clang not gcc

### Behaviour/ Breaking changes

Should work as before, no functional change. possible limitation of 32 USB interfaces (can be made dynamic, in additional commits)

### Have you tested the changes?

Yes, but I am fairly unfamiliar with the project, and some things don't work for me, not sure if related to my changes.

I'll detail the compile errors below.

### CODE REVIEW

**Comment by vintagepc** [comment]
Thanks for your submission.

I remember making this particular change before and had to revert it because it causes the linter (`clang-tidy`) to segfault when the structure definitions are "correct" according to clang. 

```
Checking parts/I2CPeripheral.cpp ...
Segmentation fault (core dumped)
```

We may need to guard these changes with `#ifdef __clang__` to switch in the appropriate definitions on compile without breaking clang-tidy - but I'm open to suggestions.

**Comment by GilesBathgate** [comment]
@vintagepc I'll see if I can keep clang/clang-tidy/gcc/cppcheck all happy! ;) If not, I'll add the #ifdefs. What bout the usbip array size?

**Comment by vintagepc** [comment]
I don't have any immediate thoughts on that, 

> @vintagepc I'll see if I can keep clang/clang-tidy/gcc/cppcheck all happy! ;) If not, I'll add the #ifdefs. What bout the usbip array size?

A quick google tells me the maximum number of endpoints (and therefore interfaces) in USB is 16, so it seems like we could just hard-code it at that with a `static constexpr` definition somewhere for organizational reasons :+1:

**Comment by GilesBathgate** [comment]
> it seems like we could just hard-code it at that with a `static constexpr` definition somewhere for organizational reasons

There is no `static constexpr` in c99, so an anonymous enum instead?

**Comment by vintagepc** [comment]
ah shoot, I forgot I hadn't ported that file over from C to C++ yet. My mistake. 

In that case just stick a #define at the top of the file :)

**Comment by GilesBathgate** [comment]
I was going to do this:

```diff
@@ -318,10 +317,11 @@ handle_usbip_req_devlist(
 
 	load_device_and_config_descriptor(p);
 
+	enum { max_usb_endpoints = 32 };
 	// get config AND interface descriptors
 	struct {
 		struct usb_configuration_descriptor config;
-		struct usb_interface_descriptor interf[32];
+		struct usb_interface_descriptor interf[max_usb_endpoints];
 	} cd;
```

but I will do a #define instead if that makes the conversion to cpp in the future simpler.

**Comment by vintagepc** [comment]
Great! Someday I'll get around to reworking it for C++ but since it USBIP works as-is it's obviously not a priority :)

**Comment by GilesBathgate** [comment]
@vintagepc I think the workflows will complete now. I'll check tomorrow.

**Review by vintagepc — APPROVED** [review]

**Pull request merged**
