### PR TITLE
Remove the need to calculate sqrt by using squared distance

### PR DESCRIPTION
**Pull request by GilesBathgate**
### Description

Minor performance tweak. When doing distance comparisons (c^2 = a^2+b^2), you can calculate c < 10, or you can do c^2 < 100.

### Behaviour/ Breaking changes

Expect the same behaviour, and probably no noticeable performance gain, but still...

### Have you tested the changes?

Yes, seems to work with MK3 as before.

### CODE REVIEW

**Comment by GilesBathgate** [comment]
Also note `(f/5)^2` = `f^2/5^2` ;)

**Comment by vintagepc** [comment]
Unfortunately the OSX compiler doesn't recognize that syntax:

```
/Users/runner/work/MK404/MK404/parts/components/PINDA.cpp:47:25: error: result of '10^2' is 8; did you mean '1e2'? [-Werror,-Wxor-used-as-pow]
                        if (fEdistSquared<(10^2))
                                           ~~^~
                                           1e2
/Users/runner/work/MK404/MK404/parts/components/PINDA.cpp:47:25: note: replace expression with '0xA ^ 2' or use 'xor' instead of '^' to silence this warning

```

**Comment by vintagepc** [comment]
... and more importantly, `^ ` is XOR, not "power"

**Comment by GilesBathgate** [comment]
@vintagepc Oh dear, schoolboy error. I've fixed it.

**Review by vintagepc — APPROVED** [review]

**Pull request merged**
